#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


#PS1
gitBranch() {
    git branch 2>/dev/null | sed -n 's/^\* \(.*\)$/ (\1)/p'
}

PS1='[\u@\h \W]\[\e[0;32m\]$(gitBranch)\[\e[0m\]\$ '


#Aliases
alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -a'
alias lf='ls -f'
alias grep='grep --color=auto'
alias vim='vim -p'

alias gcc='echo "alias of gcc";gcc -Wall -Werror -Wextra -Wvla -pedantic -std=c99'
alias g++='echo "alias of g++";g++ -std=c++20 -Wall -Wextra -Werror -pedantic -Wold-style-cast'

alias save="$HOME/Desktop/scripts/archiver/save_archi.sh"
alias clean="$HOME/Desktop/scripts/archiver/clean_archi.sh"

alias trash="$HOME/Desktop/scripts/recycle_bin/recycle_bin.sh"
alias delete="$HOME/Desktop/scripts/recycle_bin/recycle_bin.sh delete"
alias restore="$HOME/Desktop/scripts/recycle_bin/recycle_bin.sh restore"
alias empty="$HOME/Desktop/scripts/recycle_bin/recycle_bin.sh empty"

alias sswitch="$HOME/Desktop/scripts/switch_format/switch_format.sh" # style switch

alias map="$HOME/Desktop/scripts/map.sh"

alias cformat="$HOME/Desktop/scripts/mapclgf.sh"

alias cheader="$HOME/Desktop/scripts/make_header.sh"

alias switch="$HOME/Desktop/scripts/switch_format/switch_format.sh"

alias work="$HOME/Desktop/scripts/piscine_framework/piscine_manager.sh"

